[package]
name = "BGF"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.0-rc0"
glam = { version = "0.17.0", features = ["mint"] }
quad-rand = "0.2.1"